package com.novabank.core;

import com.novabank.core.model.Role;
import com.novabank.core.model.User;
import com.novabank.core.repository.UserRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The one test in this suite that runs against a real, containerized PostgreSQL instance instead
 * of H2 — every other integration test in this codebase points {@code spring.jpa.hibernate
 * .ddl-auto} at {@code create-drop} against H2, and Flyway is explicitly disabled for the entire
 * test classpath (see {@code src/test/resources/application.yml}) because the actual migration
 * SQL under {@code src/main/resources/db/migration} is PostgreSQL-specific
 * ({@code GENERATED BY DEFAULT AS IDENTITY}, etc.) and was never intended to run against H2.
 *
 * That means, prior to this test, the real migration SQL that would run in production was never
 * actually executed and verified by the test suite — H2 tests only proved the JPA entity model
 * was internally consistent with itself via Hibernate's own {@code create-drop}, not that the
 * hand-written Flyway migrations (V1 baseline schema, V2 webhook outbox, V3 refresh tokens)
 * are individually valid, apply cleanly in order, and produce a schema {@code
 * spring.jpa.hibernate.ddl-auto=validate} accepts.
 *
 * This test boots the full Spring context (real Flyway enabled, {@code ddl-auto=validate|
 * against a disposable PostgreSQL 16 container (Testcontainers), then performs one real write/
 * read through a repository to prove the resulting schema is not just "present" but usable.
 *
 * Runs only as part of {@code mvn verify} (via the failsafe plugin's {@code *IT.java} naming
 * convention — {@code mvn test} does not pick this up), and only where Docker is available; the
 * project's CI workflow runs it in a dedicated job on a Docker-equipped GitHub Actions runner.
 */
@Testcontainers
@SpringBootTest
class FlywayMigrationPostgresIT {

    @Container
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16")
            .withDatabaseName("nova_bank_it")
            .withUsername("nova_it_user")
            .withPassword("nova_it_password");

    @DynamicPropertySource
    static void registerPostgresProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", POSTGRES::getJdbcUrl);
        registry.add("spring.datasource.username", POSTGRES::getUsername);
        registry.add("spring.datasource.password", POSTGRES::getPassword);
        // src/test/resources/application.yml disables Flyway for the ENTIRE test classpath
        // (every other test runs against H2, where the real PostgreSQL-specific migration SQL
        // does not apply) — override it back on here specifically, since running the real
        // migrations against a real Postgres instance is the entire point of this test.
        registry.add("spring.flyway.enabled", () -> "true");
        // src/test/resources/application.yml fully shadows src/main/resources/application.yml
        // on the test classpath (same relative resource path; test-classes precedes classes on
        // the classpath), so main's ddl-auto=validate is NOT inherited here — it must be
        // restated explicitly to actually exercise the "Hibernate refuses to start if the
        // entity model and migrated schema disagree" guarantee this test exists to verify.
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "validate");
        registry.add("app.bootstrap.admin.password", () -> "it-test-admin-password");
    }

    @Autowired
    private UserRepository userRepository;
    @Autowired
    private PasswordEncoder passwordEncoder;

    @Test
    void applicationStartsAgainstARealPostgresInstanceWithFlywayMigrationsApplied() {
        // If V1/V2/V3 did not apply cleanly, or disagreed with the JPA entity model under
        // ddl-auto=validate, the Spring context would already have failed to start before this
        // test method ever ran.
        assertThat(userRepository).isNotNull();
    }

    @Test
    void theMigratedSchemaIsActuallyUsableForARealReadWriteRoundTrip() {
        User user = new User();
        user.setUsername("flyway_it_user");
        user.setEmail("flyway_it_user@example.com");
        user.setPasswordHash(passwordEncoder.encode("password123"));
        user.setRole(Role.CUSTOMER);
        userRepository.save(user);

        User reloaded = userRepository.findByUsername("flyway_it_user").orElseThrow();
        assertThat(reloaded.getId()).isNotNull();
        assertThat(reloaded.getRole()).isEqualTo(Role.CUSTOMER);
        assertThat(reloaded.isEnabled()).isTrue();
    }
}
