-- Baseline schema migration.
--
-- This captures the schema exactly as it was generated by Hibernate's `ddl-auto: update` in
-- prior deployments (verified by running the application against a disposable PostgreSQL 16
-- instance with `ddl-auto: create` and diffing the resulting `pg_dump --schema-only` output
-- against this file), so that adopting Flyway does not require a destructive schema recreation
-- for any existing environment. From this migration forward, `ddl-auto` is set to `validate`
-- in every profile (see application.yml) — Hibernate will refuse to start if the entity model
-- and the migrated schema ever drift apart, and all future schema changes must ship as a new
-- versioned Flyway migration rather than relying on Hibernate auto-DDL.
--
-- Constraint/index names are written out explicitly (rather than left to Hibernate's
-- autogenerated hash-based names such as `fk7i7kboanveneetad7jyhbr0a7`) so the schema stays
-- reviewable and diffable in future migrations.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'CUSTOMER', 'AUDITOR'))
);

-- Supports admin lookups and login-by-username/email; also documents the query pattern even
-- though the UNIQUE constraints above already provide a usable index for equality lookups.
CREATE INDEX idx_users_email ON users (email);

CREATE TABLE accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id        BIGINT         NOT NULL REFERENCES users (id),
    account_number VARCHAR(30)    NOT NULL,
    balance        NUMERIC(19, 2) NOT NULL,
    active         BOOLEAN        NOT NULL,
    version        BIGINT         NOT NULL DEFAULT 0,
    CONSTRAINT accounts_account_number_key UNIQUE (account_number)
);

CREATE INDEX idx_accounts_user ON accounts (user_id);

CREATE TABLE transactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    reference       VARCHAR(36)    NOT NULL,
    from_account_id BIGINT REFERENCES accounts (id),
    to_account_id   BIGINT REFERENCES accounts (id),
    type            VARCHAR(20)    NOT NULL,
    amount          NUMERIC(19, 2) NOT NULL,
    occurred_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    note            VARCHAR(255),
    CONSTRAINT transactions_reference_key UNIQUE (reference),
    CONSTRAINT transactions_type_check CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER'))
);

CREATE INDEX idx_tx_from ON transactions (from_account_id);
CREATE INDEX idx_tx_to ON transactions (to_account_id);
-- Supports statement/summary queries filtered or sorted by date, avoiding a full table scan
-- as transaction volume grows (see TransactionService listing/filtering/summary methods).
CREATE INDEX idx_tx_occurred_at ON transactions (occurred_at);

CREATE TABLE audit_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    actor          VARCHAR(64)  NOT NULL,
    action         VARCHAR(100) NOT NULL,
    account_number VARCHAR(64),
    reference      VARCHAR(64),
    details        VARCHAR(255) NOT NULL
);

-- /api/admin/audit is the primary read path for this table (paginated findAll today, filtered
-- lookups in the future) — index the columns most likely to be filtered/sorted on.
CREATE INDEX idx_audit_logs_actor ON audit_logs (actor);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);

CREATE TABLE fraud_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    event_type     VARCHAR(100) NOT NULL,
    username       VARCHAR(64),
    account_number VARCHAR(64),
    details        VARCHAR(255) NOT NULL,
    flagged        BOOLEAN      NOT NULL
);

-- /api/admin/fraud is the primary read path for this table — same rationale as audit_logs above.
CREATE INDEX idx_fraud_logs_username ON fraud_logs (username);
CREATE INDEX idx_fraud_logs_created_at ON fraud_logs (created_at);

CREATE TABLE transfer_idempotency_records (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    actor_username     VARCHAR(64)  NOT NULL,
    idempotency_key    VARCHAR(100) NOT NULL,
    request_hash       VARCHAR(64)  NOT NULL,
    transfer_reference VARCHAR(36)  NOT NULL,
    CONSTRAINT uk_transfer_idempotency_actor_key UNIQUE (actor_username, idempotency_key)
);
