-- Transactional outbox table for webhook notifications.
--
-- See com.novabank.core.model.WebhookOutboxEvent for the full rationale: this replaces a
-- synchronous HTTP call previously made from inside TransactionService.performTransfer() and
-- AccountService.updateAccountStatus() while an @Transactional method held open a live database
-- transaction on Account rows. Writing to this table is now the only side effect those methods
-- perform for a webhook-worthy event — a fast, local insert as part of the same transaction as
-- the business change, guaranteeing the outbox entry and the business change either both commit
-- or neither does. A separate scheduled process (WebhookDispatcher) delivers pending rows
-- asynchronously, off any request thread.

CREATE TABLE webhook_outbox_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    event_type   VARCHAR(100) NOT NULL,
    payload_json TEXT         NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    attempts     INTEGER      NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMP(6) WITH TIME ZONE,
    last_error   VARCHAR(500),
    CONSTRAINT webhook_outbox_events_status_check CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

-- WebhookDispatcher's poll query is "give me PENDING (and retryable FAILED) rows ordered by
-- creation time" — index the column it actually filters on.
CREATE INDEX idx_webhook_outbox_status ON webhook_outbox_events (status);
