-- Server-revocable refresh tokens (see com.novabank.core.model.RefreshToken).
--
-- Only a SHA-256 hash of the token is ever stored (token_hash) — never the raw value — so a
-- database read/backup leak alone cannot be replayed as a valid refresh token. Closes Critical
-- Issue #5 from the code review: previously a leaked JWT access token remained valid for its
-- full 24h lifetime with no server-side kill switch. Access tokens are now short-lived (15 min,
-- see application.yml) and this table gives the longer-lived refresh token an explicit
-- revocation/rotation mechanism instead.

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    token_hash VARCHAR(64)  NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
-- Supports a future scheduled cleanup job purging long-expired rows.
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
